# Generated by Django 2.0.2 on 2018-08-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arroz', models.CharField(max_length=20)),
                ('feijao', models.CharField(max_length=20)),
                ('guarnicao', models.CharField(max_length=40)),
                ('proteina', models.CharField(max_length=20)),
                ('proteina2', models.CharField(max_length=20)),
                ('opcaoVegetariana', models.CharField(max_length=20)),
                ('salada', models.CharField(max_length=20)),
                ('sobremesa', models.CharField(max_length=20)),
                ('suco', models.CharField(max_length=20)),
                ('data', models.DateField(verbose_name='Data Refeição')),
                ('diaDaSemana', models.CharField(max_length=20)),
                ('aviso', models.CharField(max_length=140)),
            ],
        ),
    ]
