# Generated by Django 2.0.2 on 2018-08-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandejao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeHorario', models.CharField(max_length=20)),
                ('horarioInicio', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='refeicao',
            name='horario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bandejao.Horarios'),
        ),
    ]
