# Generated by Django 2.0.2 on 2018-08-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
	

    dependencies = [
        ('bandejao', '0002_auto_20180830_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
    ]
