# Generated by Django 2.0.2 on 2018-08-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('bandejao', '0003_auto_20180830_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horario',
            new_name='Horarios',
        ),
    ]
