# Generated by Django 2.1 on 2018-08-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.PositiveIntegerField(unique=True)),
                ('senha', models.CharField(max_length=16)),
                ('salt', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('foto', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('tem_troco', models.BooleanField()),
                ('tem_cartao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.FloatField()),
                ('foto_prod', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('anunciante_horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anuncios.Anunciante')),
                ('segunda', models.CharField(max_length=140)),
                ('terca', models.CharField(max_length=140)),
                ('quarta', models.CharField(max_length=140)),
                ('quinta', models.CharField(max_length=140)),
                ('sexta', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='anunciante_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Anunciante'),
        ),
    ]
